# NUMPY - Numerical Python (storage and operation on dense data buffers)

## NumPy arrays form the core of nearly the entire ecosystem of data science tools in Python.

In [13]:
import array as np
L  =  list(range(1000))
A = array.array('i', L)
A;

In [19]:
import numpy as np
np.array([1,2,3,4], dtype=np.float32)

array([1., 2., 3., 4.], dtype=float32)

In [26]:
np.array([range(i,i+3,1) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [27]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [32]:
np.ones((3,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [42]:
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [44]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [43]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [52]:

np.random.random((3,3))

array([[0.33063821, 0.67913686, 0.78189366],
       [0.4790349 , 0.93252866, 0.27139316],
       [0.19035464, 0.28173843, 0.1816154 ]])

In [54]:
#creating a 3x3 array of normally distributed pseudorandom values with mean 
# 0, standard deviation of 1 
np.random.normal(0,1,(3,3))

array([[ 0.50937504, -0.75666673,  0.01771087],
       [ 1.6984109 ,  0.87973828,  1.24104467],
       [-0.02119712, -1.41674157,  0.69559241]])

In [58]:
np.random.randint(0,10,(3,3))

array([[8, 2, 5],
       [6, 5, 1],
       [0, 4, 7]])

In [60]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [62]:
np.empty(3)

array([1., 1., 1.])

In [78]:
import numpy as np
rng = np.random.default_rng(seed=1701)
x1 = rng.integers(10, size=6)
x2 = rng.integers(10, size=(3,4))
x3 = rng.integers(10, size=(3,4,5))
print(f"ID is {x1} \tand 2D is \n{x2} \tand 3D is \n{x3}")

ID is [9 4 0 3 8 6] 	and 2D is 
[[3 1 3 7]
 [4 0 2 3]
 [0 0 6 9]] 	and 3D is 
[[[4 3 5 5 0]
  [8 3 5 2 2]
  [1 8 8 5 3]
  [0 0 8 5 8]]

 [[5 1 6 2 3]
  [1 2 5 6 2]
  [5 2 7 9 3]
  [5 6 0 2 0]]

 [[2 9 4 3 9]
  [9 2 2 4 0]
  [0 3 0 0 2]
  [3 2 7 4 7]]]


In [79]:
x1

array([9, 4, 0, 3, 8, 6])

In [81]:
x1[-1]

np.int64(6)

In [82]:
x2

array([[3, 1, 3, 7],
       [4, 0, 2, 3],
       [0, 0, 6, 9]])

In [86]:
x2[2,-2]

np.int64(6)

In [88]:
x2[0,0] = 12
x2

array([[12,  1,  3,  7],
       [ 4,  0,  2,  3],
       [ 0,  0,  6,  9]])

In [92]:
x1[1]= 3.142
x1

array([9, 3, 0, 3, 8, 6])

In [93]:
x1

array([9, 3, 0, 3, 8, 6])

In [94]:
x1[:3]

array([9, 3, 0])

In [95]:
x1[3:]

array([3, 8, 6])

In [96]:
x1[1:4]

array([3, 0, 3])

In [101]:
x1[0::3]

array([9, 3])

In [103]:
x1[::-1]

array([6, 8, 3, 0, 3, 9])

In [104]:
x2

array([[12,  1,  3,  7],
       [ 4,  0,  2,  3],
       [ 0,  0,  6,  9]])

In [105]:
x2[:2, :3]

array([[12,  1,  3],
       [ 4,  0,  2]])

In [106]:
x2[::-1,::-1]

array([[ 9,  6,  0,  0],
       [ 3,  2,  0,  4],
       [ 7,  3,  1, 12]])

In [108]:
x2[:1,:3]

array([[12,  1,  3]])

In [111]:
x2[:,3]

array([7, 3, 9])

In [112]:
x2[0,:]

array([12,  1,  3,  7])

In [115]:
x2_sub=x2[:2,:2]
print(x2_sub)

[[12  1]
 [ 4  0]]


In [117]:
x2_sub[0,0] = 99
print(x2)

[[99  1  3  7]
 [ 4  0  2  3]
 [ 0  0  6  9]]


In [119]:
x2_sub_copy = x2[:2,:2].copy()
print(x2_sub_copy)

[[99  1]
 [ 4  0]]


In [121]:
x2_sub_copy[0,0]=23
print(x2_sub_copy)

[[23  1]
 [ 4  0]]


In [123]:
print(x2_sub)

[[99  1]
 [ 4  0]]


In [125]:
x2_list_copy=x2_sub[:]
print(x2_list_copy)

[[99  1]
 [ 4  0]]


In [127]:
x2_list_copy[0,1]=13
print(x2_list_copy)

[[99 13]
 [ 4  0]]


In [128]:
print(x2_sub)

[[99 13]
 [ 4  0]]


In [136]:
grid = np.arange(1,10).reshape(3,3)
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [142]:
x = np.array([1, 2, 3])
print(x.size)

3


In [139]:
x.reshape(1,3)

array([[1, 2, 3]])

In [140]:
x.reshape(3,1)

array([[1],
       [2],
       [3]])

In [144]:
np.newaxis()

Type:        NoneType
String form: None
Docstring:   <no docstring>

In [145]:
x[np.newaxis,:]

array([[1, 2, 3]])

In [146]:
x[:,np.newaxis]

array([[1],
       [2],
       [3]])

In [152]:
x = np.array([1,2,3])
y = np.array([3,4,5])
np.concatenate([x,y])

array([1, 2, 3, 3, 4, 5])

In [153]:
z = np.array([99,99,99])

In [154]:
np.concatenate([x,y,z])

array([ 1,  2,  3,  3,  4,  5, 99, 99, 99])

In [156]:
grid = np.array([[1, 2, 3],
                [4, 5, 6]])
print(grid
    )

np.concatenate([grid,grid])

[[1 2 3]
 [4 5 6]]


array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [158]:
np.concatenate([grid,grid],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [168]:
x = [7,21,13]
np.vstack([x,grid])

array([[ 7, 21, 13],
       [ 1,  2,  3],
       [ 4,  5,  6]])

In [167]:
y = np.array([[99],
            [99]])
np.hstack([grid, y])

array([[ 1,  2,  3, 99],
       [ 4,  5,  6, 99]])

In [174]:
x = [1,2,3,99,3,2,1]
x1,x2,x3 = np.split(x,[3,5])
print(x3
     )

[2 1]


In [177]:
grid = np.arange(16).reshape(4,4)
print(grid)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [181]:
upper , lower = np.vsplit(grid,[2])
print(upper, lower)

[[0 1 2 3]
 [4 5 6 7]] [[ 8  9 10 11]
 [12 13 14 15]]


In [182]:
left, right = np.hsplit(grid, [2])
print(left, right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]] [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [191]:
import numpy as np
rng = np.random.default_rng(seed=1701)

def compute_reciprocals(values):
    output = np.empty(len(values))
    print(output)

    for i in range(len(values)):
        output[i] = 1.0/ values[i]
    return output

values = rng.integers(1,10,size=5)
compute_reciprocals(values)
    


[4.4e-323 2.0e-323 4.9e-324 1.5e-323 4.0e-323]


array([0.11111111, 0.25      , 1.        , 0.33333333, 0.125     ])

In [192]:
big_array = rng.integers(1, 100, size=1_000_000)
%timeit compute_reciprocals(big_array)


[0. 0. 0. ... 0. 0. 0.]
[0.00000e+000 5.32266e-317 9.58265e-319 ... 0.00000e+000 0.00000e+000
 0.00000e+000]
[0.01492537 0.025      0.0625     ... 0.015625   0.03846154 0.01639344]
[0.01492537 0.025      0.0625     ... 0.015625   0.03846154 0.01639344]
[0.01492537 0.025      0.0625     ... 0.015625   0.03846154 0.01639344]
[0.01492537 0.025      0.0625     ... 0.015625   0.03846154 0.01639344]
[0.01492537 0.025      0.0625     ... 0.015625   0.03846154 0.01639344]
[0.01492537 0.025      0.0625     ... 0.015625   0.03846154 0.01639344]
1.58 s ± 44.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [193]:
print(compute_reciprocals(values))
print(1/values)

[0.11111111 0.25       1.         0.33333333 0.125     ]
[0.11111111 0.25       1.         0.33333333 0.125     ]
[0.11111111 0.25       1.         0.33333333 0.125     ]


In [194]:
%timeit (1.0 /big_array)

1.59 ms ± 88.1 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [197]:
np.arange(5)/np.arange(1,6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [199]:
x = np.arange(9).reshape(3,3)
2 **x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

# Exploring NumPy Ufuncs

## Ufuncs exist in two flavors unary ufuncs, operates on single input and binary ufuncs which operates on two inputs



In [204]:
x = np.arange(4)
print(x)
for i in x:
    print(i//2)

[0 1 2 3]
0
0
1
1


In [205]:
for a in x:
    print(f"{-a}")

0
-1
-2
-3


In [206]:
a % 2

np.int64(1)

In [209]:
print(x)
np.add(x,2)

[0 1 2 3]


array([2, 3, 4, 5])

In [210]:
np.subtract(x,2)

array([-2, -1,  0,  1])

In [212]:
np.multiply(x,3)

array([0, 3, 6, 9])

In [214]:
np.divide(x,2)

array([0. , 0.5, 1. , 1.5])

In [215]:
np.floor_divide(x,2)

array([0, 0, 1, 1])

In [216]:
np.power(x,2)

array([0, 1, 4, 9])

In [217]:
np.mod(x,2)

array([0, 1, 0, 1])

## Absolute Value
x = np.array([for _in range(-2,2,1)])
print(x)

In [221]:
x = np.array([_** 1 for _ in range(-2,3,1)])

print(x)

[-2 -1  0  1  2]


In [222]:
abs(x)

array([2, 1, 0, 1, 2])

In [223]:
np.absolute(x
           )

array([2, 1, 0, 1, 2])

In [224]:
# Magnitude of a vector
x = np.array([3 -4j, 4 -3j, 2 +0j, 0 +1j])
np.abs(x)

array([5., 5., 2., 1.])

In [231]:
theta = np.linspace(0, np.pi,4)
print(theta)

[0.         1.04719755 2.0943951  3.14159265]


In [235]:
x = [1,2, 3]
np.exp(x)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [5]:
import numpy as np
x = np.array([2,3,4])

np.log(x)

array([0.69314718, 1.09861229, 1.38629436])

In [240]:
np.log10(x)

array([0.30103   , 0.47712125, 0.60205999])

In [246]:
np.exp(x) -1


array([ 6.3890561 , 19.08553692, 53.59815003])

In [247]:
np.expm1(x)

array([ 6.3890561 , 19.08553692, 53.59815003])

In [6]:
from scipy import special as sp
sp.gamma(x)

array([1., 2., 6.])

In [16]:
x = np.arange(5)
print(x)
y = np.empty(5)
np.multiply(x,10,out=y)
print(y)

[0 1 2 3 4]
[ 0. 10. 20. 30. 40.]


In [20]:
y = np.zeros(10)
np.power(2,x,out=y[::2])

array([ 1.,  2.,  4.,  8., 16.])

In [5]:
import numpy as np
x = np.arange(1, 6)
np.add.reduce(x)

np.int64(15)

In [7]:
y = np.arange(1,6)
np.multiply.outer(y,x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])